Repository Spectrum-CETB/LesKollab, pull requests merged in 2021-03, with the labels that each got.

#25 Added 'About us' in index.php
  index.php
Labels: Level2, gssoc21

#33 Added Footer on index.php
  assets/css/all.min.css
  assets/js/all.min.js
  index.php
Labels: Level2, gssoc21

#22 Added Contributor
  README.md
Labels: Level1, gssoc21

#41 Issue #3 Fixed - Modal Form Created and linked to "Find a Partner" Button
  assets/css/styles.css
  index.php
Labels: Level3, gssoc21

#45 pull updated version and done required changes
  index.php
Labels: Level2, gssoc21

#44 issue #36 solution
  index.php
Labels: Level2, gssoc21

#48 image duplicacy resolved!
  scripts/Register.php
  scripts/post-project.php
Labels: Level2, gssoc21

#50 Issue#46 fixed "Added brand logo on navbar and footer.
  assets/images/logo1.png
  assets/images/logo_footer.png
  index.php
Labels: Level2, gssoc21

#51 Update README.md
  README.md
Labels: Level0, gssoc21
