Repository Spectrum-CETB/LesKollab, pull requests merged in 2021-04, with the labels that each got.

#57 [Gssoc'21] Added Contact Us section
  index.php
  leskollab.sql
  scripts/contact.php
Labels: Level2, gssoc21

#60 Gssoc'21 Added the Password validation by js in Register page
  assets/css/styles.css
  assets/js/register.js
  index.php
Labels: Level2, gssoc21

#66 [Gssoc'21] Added show Password feature
  assets/js/register.js
  index.php
Labels: Level2, gssoc21

#63 Issue#62 "Added login functionality for admin."
  Explore/index.php
  admin/admin_dashboard.php
  admin/admin_login.php
  index.php
  leskollab.sql
Labels: Level3, gssoc21

#35 schema is updated, import new schema(loskollab.sql) in localhost
  Explore/index.php
  leskollab.sql
  scripts/post-project.php
Labels: Level3, gssoc21

#65 organized_code
  Explore/index.php
  components/common/footer.php
  components/common/header.php
  components/common/modals.php
  components/common/navbar.php
Labels: Level2, gssoc21

#76 [Gssoc'21] Added the dark mode with toggle button
  assets/css/darkmode.css
  assets/css/styles.css
  assets/js/darkmode.js
  index.php
Labels: Level2, gssoc21

#79 Fixes #68 Added Primary Key Constraint to contact table
  leskollab.sql
Labels: Level2, gssoc21

#77 Edit Project (Post)
  Explore/index.php
  scripts/edit-project.php
Labels: Level2, gssoc21

#80 [Gssoc'21] Enhance the footer as much as possible
  assets/css/styles.css
  index.php
Labels: Level3, gssoc21

#81 Fixes Issue#78 Applied Validation in Contact Us Form
  index.php
Labels: Level2, gssoc21

#84 [Gssoc21]Added the 404 page and the code to handle 404 eror
  .htaccess
  404.php
Labels: Level3, gssoc21

#86 Fixes Issue#82 Brand Logo added on navbar in Explore/index.php page and navbar enhanced.
  Explore/index.php
Labels: Level2, gssoc21

#90 [Gssoc'21] Added Faq's section in index.php
  assets/css/styles.css
  assets/js/faq.js
  index.php
Labels: Level3, gssoc21

#94 Readme modified
  README.md
Labels: Level1, gssoc21

#95 [Gssoc'21] Added the Preloader to website
  index.php
Labels: Level2, gssoc21

#98 [Gssoc] Added the Back to top button
  assets/css/styles.css
  index.php
Labels: Level2, gssoc21

#91 Fixes Issue#64 Added Admin Dashboard showing number of users, projects and messages …
  admin/admin_dashboard.php
  admin/admin_login.php
  admin/header.php
  assets/css/header.css
Labels: Level3, gssoc21

#100 [Gssoc'21] Added a Project description Page
  Explore/assets/css/all.min.css
  Explore/assets/img/logo1.png
  Explore/assets/js/all.min.js
  Explore/checkProject.php
  Explore/index.php
  Explore/projects/My Portfolio Website/1618678811bg.png
  Explore/projects/Test1/1618654548lescolab.png
Labels: Level3, gssoc21

#102 Fixes Issue#93 Added logout functionality for admin and sidebar of admin enhanced
  admin/admin_dashboard.php
  admin/admin_login.php
  admin/header.php
Labels: Level2, gssoc21

#106 Confirmation alert Before Logout
  Explore/index.php
Labels: Level2, gssoc21

#105 Project Details Ui Enhanced
  Explore/checkProject.php
Labels: Level2, gssoc21

#107 Fixes Issue#103 Navbar on index.php(Home Page) enhanced.
  index.php
Labels: Level2, gssoc21

#109 Improve Ui of Project cards
  Explore/index.php
Labels: Level2, gssoc21

#99 Complete Info of loggedin User!
  Explore/index.php
  Explore/user_info.php
  components/common/navbar.php
  scripts/update_user.php
Labels: Level3, gssoc21

#113 Fixes Issue#92 Added View Messages functionality in admin panel
  admin/header.php
  admin/user_messages.php
Labels: Level2, gssoc21

#118 Added Download Contact as csv feature
  Explore/index.php
  admin/admin_dashboard.php
  admin/downloadcontact.php
Labels: Level2, gssoc21

#117 Resolved bug and resized logo
  assets/css/styles.css
  index.php
Labels: Level2, gssoc21

#119 Fixes Issue#114 Added Generate Report functionality for admin.
  admin/generate_report.php
  admin/header.php
  leskollab.sql
Labels: Level2, gssoc21

#121 Delete button for project
  Explore/index.php
  scripts/delete-project.php
Labels: Level2, gssoc21
