Repository Spectrum-CETB/LesKollab, pull requests merged in 2021-05, with the labels that each got.

#124 Download project data as csv file
  admin/admin_dashboard.php
  admin/downloadproject.php
Labels: Level2, gssoc21

#126 Better UI for Error / Success Message
  Explore/index.php
  components/common/messages.php
  index.php
  logout.php
  scripts/Login.php
  scripts/Register.php
  scripts/contact.php
Labels: Level3, gssoc21

#131 Proper Step by Step Video for Project Set up
  README.md
Labels: Level1, gssoc21

#134 Ui enhancement in footer.
  assets/css/styles.css
  index.php
Labels: Level2, gssoc21

#139 added Confirmation alert in User Dashboard
  components/common/navbar.php
Labels: Level2, gssoc21

#138 added Confirmation alert in admin Dashboard
  admin/header.php
Labels: Level2, gssoc21

#142 Bug in User Dashboard
  Explore/index.php
  components/common/header.php
  components/common/navbar.php
Labels: Level2, gssoc21

#145 added a our teams section on home page
  images/Affluent-Women-Mailing-Lists.jpg
  images/Sam-Revilter.jpg
  images/person-2.jpg
  images/team4-large.jpg
  index.php
Labels: Level3, gssoc21

#146 added edit profile section
  Explore/index.php
  scripts/edit-profile.php
Labels: Level3, gssoc21

#149 fixed errors on admin login
  admin/admin_login.php
Labels: Level2, gssoc21

#150 Addded a navbar in Admin login
  admin/admin_login.php
  index.php
Labels: Level2, gssoc21

#156 added footer in checkProject.php
  Explore/checkProject.php
Labels: Level2, gssoc21

#153 added a sweet alert before deleting project
  Explore/index.php
Labels: Level2, gssoc21

#155 added navbar in admin dashboard
  admin/header.php
Labels: Level2, gssoc21

#160 added navbar with darkmode toggle in check project,php
  Explore/checkProject.php
Labels: Level2, gssoc21

#158 Adding Dark mode in Admin Login
  admin/admin_login.php
  assets/css/darkmode.css
  index.php
Labels: Level2, gssoc21

#162 added show password feature in admin login
  admin/admin_login.php
Labels: Level2, gssoc21

#165 Responsiveness of check project.php page
  Explore/checkProject.php
  Explore/projects/CodeSmashers Blog/1621966312blog.png
  assets/css/darkmode.css
Labels: Level2, gssoc21

#169 added dark mode in admin dashboard
  admin/header.php
Labels: Level2, gssoc21

#170 Modified the ui of user_info
  Explore/projects/Something/1622038118pic1.jpg
  Explore/user_info.php
Labels: Level2, gssoc21

#171 Added responsiveness to index.php
  index.php
Labels: Level2, gssoc21

#173 added hover animations to navbar
  index.php
Labels: Level2, gssoc21
